services:
  load-balancer:
      image: nginx:latest
      container_name: load-balancer
      ports:
        - "8080:80" 
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on: 
        - auth-service
  database:
    image: mongo:latest
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    volumes:
      - ./auth-service:/usr/src/app
    command: cargo watch -x run
    depends_on:
      - database
    environment:
      SECRET_SESSION: ${SECRET_SESSION}
      DATABASE_URL_AUTH_SERVICE: ${DATABASE_URL_AUTH_SERVICE}
