services:
  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - auth-service
      - users-service
      - events-service
      - tickets-service
      - notifications-service
      - payments-service
      - backups-service

  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile.prod
    container_name: auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/auth/health"]
      interval: 10s        
      timeout: 5s         
      retries: 3        
      start_period: 5s  
    environment:
      JWT_INTERNAL_SIGNATURE: ${JWT_INTERNAL_SIGNATURE}
      JWT_EXTERNAL_SIGNATURE: ${JWT_EXTERNAL_SIGNATURE}
      DATABASE_URL_AUTH_SERVICE: ${DATABASE_URL_AUTH_SERVICE}

  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile.prod
    container_name: users-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/users/health"]
      interval: 10s        
      timeout: 5s         
      retries: 3        
      start_period: 5s  
    environment:
      JWT_INTERNAL_SIGNATURE: ${JWT_INTERNAL_SIGNATURE}
      JWT_EXTERNAL_SIGNATURE: ${JWT_EXTERNAL_SIGNATURE}
      DATABASE_URL_USERS_SERVICE: ${DATABASE_URL_USERS_SERVICE}

  events-service:
    build:
      context: .
      dockerfile: events-service/Dockerfile.prod
    container_name: events-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/events/health"]
      interval: 10s        
      timeout: 5s         
      retries: 3        
      start_period: 5s  
    environment:
      JWT_INTERNAL_SIGNATURE: ${JWT_INTERNAL_SIGNATURE}
      JWT_EXTERNAL_SIGNATURE: ${JWT_EXTERNAL_SIGNATURE}
      DATABASE_URL_EVENTS_SERVICE: ${DATABASE_URL_EVENTS_SERVICE}

  tickets-service:
    build:
      context: .
      dockerfile: tickets-service/Dockerfile.prod
    container_name: tickets-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/tickets/health"]
      interval: 10s        
      timeout: 5s         
      retries: 3        
      start_period: 5s
    environment:
      JWT_INTERNAL_SIGNATURE: ${JWT_INTERNAL_SIGNATURE}
      JWT_EXTERNAL_SIGNATURE: ${JWT_EXTERNAL_SIGNATURE}
      DATABASE_URL_TICKETS_SERVICE: ${DATABASE_URL_TICKETS_SERVICE}

  notifications-service:
    build:
      context: .
      dockerfile: notifications-service/Dockerfile.prod
    container_name: notifications-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/notifications/health"]
      interval: 10s        
      timeout: 5s         
      retries: 3        
      start_period: 5s
    environment:
      JWT_INTERNAL_SIGNATURE: ${JWT_INTERNAL_SIGNATURE}
      JWT_EXTERNAL_SIGNATURE: ${JWT_EXTERNAL_SIGNATURE}
      DATABASE_URL_NOTIFICATIONS_SERVICE: ${DATABASE_URL_NOTIFICATIONS_SERVICE}
      MAIL_HOSTNAME: ${MAIL_HOSTNAME}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

  payments-service:
    build:
      context: .
      dockerfile: payments-service/Dockerfile.prod
    container_name: payments-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/payments/health"]
      interval: 10s        
      timeout: 5s         
      retries: 3        
      start_period: 5s
    environment:
      JWT_INTERNAL_SIGNATURE: ${JWT_INTERNAL_SIGNATURE}
      JWT_EXTERNAL_SIGNATURE: ${JWT_EXTERNAL_SIGNATURE}
      DATABASE_URL_PAYMENTS_SERVICE: ${DATABASE_URL_PAYMENTS_SERVICE}

  backups-service:
    build:
      context: .
      dockerfile: backups-service/Dockerfile.prod
    container_name: backups-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/backups/health"]
      interval: 10s        
      timeout: 5s         
      retries: 3        
      start_period: 5s
    environment:
      JWT_INTERNAL_SIGNATURE: ${JWT_INTERNAL_SIGNATURE}
      JWT_EXTERNAL_SIGNATURE: ${JWT_EXTERNAL_SIGNATURE}
      DATABASE_URL_BACKUPS_SERVICE: ${DATABASE_URL_BACKUPS_SERVICE}